### ISSUE TITLE
Can't call depositWithSignature because nonReentranct modifier

### ISSUE THREAD

**Issue by devlancer412** [chimera-defi/SharedDeposit#19]
This function use nonReentrant modifier and calls deposit function. Also deposit function uses nonReentrant modifier. So when call this function, always return `ReentrancyGuard: reentrant call` Error

https://github.com/chimera-defi/SharedDeposit/blob/1fe4278ab14aac6d9365b102752c130b1256ebee/contracts/v2/core/WSGEth.sol#L41
https://github.com/chimera-defi/SharedDeposit/blob/1fe4278ab14aac6d9365b102752c130b1256ebee/contracts/v2/core/WSGEth.sol#L48

**Comment by chimera-defi** [comment]
Any luck fixing this?

**Comment by devlancer412** [comment]
So do you want me to handle this? :)
